---
AWSTemplateFormatVersion: 2010-09-09
Description: EKS Managed Nodes

Mappings:
  ServicePrincipalPartitionmap:
    aws:
      EC2: ec2.amazonaws.com
      EKS: eks.amazonaws.com

Parameters:
  VpcStackName:
    Type: String
    Default: eks-vpc

  ClusterStackName:
    Type: String
    Default: eks-cluster

  ClusterName:
    Type: String
    Description: Name of k8s cluster
    Default: dev

  KeyPairName:
    Type: String
    Description: Name of an existing EC2 key pair (for SSH access to the worker node instance)
    Default: aws-ec2

  NodeGroupName:
    Type: String
    Description: Unique identifier for the Node Group.
    Default: nodegrp1

  NodeVolumeSize:
    Type: Number
    Default: 80
    Description: Node volume size

  NodeAutoScalingGroupDesiredCapacity:
    Type: Number
    Default: 2
    Description: Desired capacity of Node Group ASG.

  NodeAutoScalingGroupMaxSize:
    Type: Number
    Default: 3
    Description: Maximum size of Node Group ASG. Set to at least 1 greater than NodeAutoScalingGroupDesiredCapacity.

  NodeAutoScalingGroupMinSize:
    Type: Number
    Default: 1
    Description: Minimum size of Node Group ASG.
  
  NodeInstanceType:
    Type: String
    Default: t3.medium

  NodeImageIdSSMParam:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/eks/optimized-ami/1.22/amazon-linux-2/recommended/image_id
    Description: AWS Systems Manager Parameter Store parameter of the AMI ID for the worker node instances. Change this value to match the version of Kubernetes you are using.

Resources:

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              Iops: 3000
              # Throughput: 125
              VolumeSize: !Ref NodeVolumeSize
              VolumeType: gp3
        ImageId: !Ref NodeImageIdSSMParam
        # InstanceType: !Ref NodeInstanceType
        KeyName: !Ref KeyPairName
        MetadataOptions:
          HttpPutResponseHopLimit: 2
          HttpTokens: optional
        SecurityGroupIds:
          - Fn::ImportValue: 
              Fn::Sub: ${ClusterStackName}-ClusterSecurityGroupId
          - !Ref SSH
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub '${ClusterName}-${NodeGroupName}-Node'
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub '${ClusterName}-${NodeGroupName}-Node'
          - ResourceType: network-interface
            Tags:
              - Key: Name
                Value: !Sub '${ClusterName}-${NodeGroupName}-Node'
      LaunchTemplateName: !Sub '${AWS::StackName}'

  ManagedNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Sub ${ClusterName}
      InstanceTypes:
        - !Ref NodeInstanceType
      LaunchTemplate:
        Id: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      NodeRole: !GetAtt NodeInstanceRole.Arn
      NodegroupName: !Ref NodeGroupName
      ScalingConfig:
        DesiredSize: !Ref NodeAutoScalingGroupDesiredCapacity
        MaxSize: !Ref NodeAutoScalingGroupMaxSize
        MinSize: !Ref NodeAutoScalingGroupMinSize
      Subnets:
        'Fn::Split':
            - ','
            - Fn::ImportValue:
                !Sub  '${VpcStackName}-PrivateSubnetIds'

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy    # rights about vpc-cni
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}/NodeInstanceRole"
  SSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH access" # Required
      GroupName: !Sub '${AWS::StackName}-remoteAccess'
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: "Allow SSH access to managed worker nodes in group"
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}/SSH"
      VpcId: !ImportValue
        'Fn::Sub': '${VpcStackName}-VpcId'