--- 
AWSTemplateFormatVersion: '2010-09-09'
Description: EKS cluster using a VPC with two private subnets

# VPC Stack name: eks-vpc
# cluster Stack Name: eck-cluster

Parameters:

  ClusterName:
    Type: String
    Description: Name of k8s cluster
    Default: dev

  KeyPairName:
    Type: String
    Description: Name of an existing EC2 key pair (for SSH access to the worker node instance)
    Default: aws-ec2

Resources:

#==========================================================================================#
# Control Plane
#==========================================================================================#
  ControlPlane:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub '${ClusterName}'
      Version: "1.22"
      RoleArn: !GetAtt ControlPlaneRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
        SubnetIds:
        - Fn::ImportValue 

  ControlPlaneRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service:
              - eks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      RoleName: !Sub '${AWS::StackName}-ControlPlaneRole'

#==========================================================================================#
# Control Plane Security Group
#==========================================================================================#
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the elastic network interfaces between the control plane and the worker nodes
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ControlPlaneSecurityGroup"


Outputs:
  ControlPlaneSecurityGroupId:
    Description: Security group for the cluster control plane communication with worker nodes
    Value: !GetAtt ControlPlaneSecurityGroup.GroupId