AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  IAM role for serviceaccount "kube-system/aws-load-balancer-controller"

Parameters:

  OidcProviderURL:
    Description: Cluster OIDC Provider URL
    Type: String
    Default: ""

  OidcPrividerArn:
    Description: OIDC Provider ARN
    Type: String
    Default: ""

Resources:
  Role1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                oidc.eks.ap-northeast-2.amazonaws.com/id/E1961A60F459D071C8A264E2CE519837:aud: sts.amazonaws.com
                oidc.eks.ap-northeast-2.amazonaws.com/id/E1961A60F459D071C8A264E2CE519837:sub: system:serviceaccount:kube-system:aws-load-balancer-controller
            Effect: Allow
            Principal:
              Federated: >-
                arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.ap-northeast-2.amazonaws.com/id/E1961A60F459D071C8A264E2CE519837
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::${AWS::AccountId}:policy/AWSLoadBalancerControllerIAMPolicy
Outputs:
  Role1:
    Value:
      Fn::GetAtt: Role1.Arn
